version: "3"
services:
  app:
    container_name: vizsgaremek
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
      - ../frontend/dist/frontend/:/app/public
    ports:
      - 3000:3000
